### ISSUE TITLE
Selection of key points

### ISSUE THREAD

**Issue by kkk241-q** [Chiaraplizz/ST-TR#15]
There are 18 key points used in openpose in your paper. I want to pick out the key points only for the arms, plus the key points for the hands. How do you make them? Thank you

**Comment by Chiaraplizz** [comment]
Hi, 

I used the keypoints already provided in ST-GCN (https://arxiv.org/abs/1801.07455) (Kinetics-skeleton), thus unfortunately I can't help you for this step. 

Chiara
