### ISSUE TITLE
The code of Sec. V(E)

### ISSUE THREAD

**Issue by 1iuhongzhe** [Chiaraplizz/ST-TR#19]
I want to use spatial TR as an augmentation to improve my code, and i have seen the paper(Sec. V(E)), but i cant find the precise location. Could you help me to find where it is? Thanks a lot.

**Comment by Chiaraplizz** [comment]
Hi, 

Sorry for my delay in the response. If you set  only_temporal_attention: False in the configuration file, it automatically concatenates features obtained both from self-attention and from standard convolution.

Chiara
