### ISSUE TITLE
Difference between gendata and preprocess

### ISSUE THREAD

**Issue by zhengthomastang** [Chiaraplizz/ST-TR#20]
For the NTU RGB+D datasets, there are `XXX_gendata.py` and `preprocess_XXX.py` which read the same inputs and produce the same outputs. What are their differences and how the results differ if training on the corresponding `.npy` and `.label` files generated?

**Comment by Chiaraplizz** [comment]
Hi! 
The preprocess_XXX.py already includes the preprocessing step (l. 143, fp = pre_normalization(fp)). If you instead use XXX_gendata.py, you should run the pre-normalization step on the generated data.

Chiara
