### ISSUE TITLE
how to set arg.weights: when I test the network?

### ISSUE THREAD

**Issue by jianghongcheng** [Chiaraplizz/ST-TR#28]
Becasue I did not load the model's weight when I test the code, the loss is too large. I am wondering how to load the trained model to test process. Whould you please solve it?

**Comment by yogeshr59** [comment]
Hi @jianghongcheng, Assuming from this question you've trained the network. Can you please help me with running the code for the same? I would be greatful.

**Comment by Chiaraplizz** [comment]
Hi, 

You should pass to the model the args.weights by selecting the path where you are storing your weights. 

Chiara
