### ISSUE TITLE
code can't run

### ISSUE THREAD

**Issue by 1274739295** [Chiaraplizz/ST-TR#29]
When I run the code, no matter which of the three data sets I use, I get to epoch with the following problems. Using only the node and using the joint data of the node and the skeleton results in an error at 10 epoch. So I wonder if the code is storing other unimportant data during execution, please kindly comment.

RuntimeError:CUDA out of memory.Tried to allocate 29.38 MiB (GPU 0; 7.79 GiB total capacity; 6.61 GiB already allocated;21.38 MiB free; 91.98 MiB cached)

**Comment by Chiaraplizz** [comment]
Hi, 

Did you try to reduce the batch size?

Chiara
